markdown: kramdown
theme: jekyll-theme-minimal

title: Eric Guillaume Vidot
logo: github_profile_img.png
description: Certifiability. Artificial Intelligence. Machine Learning. Deep Learning.
email: 
  - [eric.vidot@irit.fr](mailto:eric.vidot@irit.fr)
  - [eric-guillaume.vidot@airbus.com](mailto:eric-guillaume.vidot@airbus.com) 
github_page: Link to [my github page](https://github.com/guillaumevidot) 
google_analytics: UA-150659735-1
