theme: jekyll-theme-minimal

title: Eric Guillaume Vidot
description: I am a PhD student at Airbus and IRIT. Email: eric.vidot@irit.fr / eric-guillaume.vidot@airbus.com
google_analytics: UA-150659735-1
